#include QMK_KEYBOARD_H


enum layers {
    _QWERTY,
    _SWE,
    // _NUMPAD,
    _LOWER,
    _RAISE,
    _ADJUST,
};

enum custom_keycodes {
    QWERTY = SAFE_RANGE,
    SWE,
    LOWER,
    RAISE,
    ADJUST,
    PRVWD,
    NXTWD,
    LSTRT,
    LEND,
    DLINE
};

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
/*
 * ,----------------------------------------------------------------------------------------------------------------------.
 * | GRV  |  1   |  2   |  3   |  4   |  5   | MINS |                    | EQL  |  6   |  7   |  8   |  9   |  0   | BSPC |
 * |------+------+------+------+------+------+------+--------------------+------+------+------+------+------+------+------|
 * | TAB  |  Q   |  W   |  E   |  R   |  T   | LBRC |                    | RBRC |  Y   |  U   |  I   |  O   |  P   | DEL  |
 * |------+------+------+------+------+------+------+--------------------+------+------+------+------+------+------+------|
 * |LGUI_T|  A   |  S   |  D   |  F   |  G   | HOME |                    | PGUP |  H   |  J   |  K   |  L   | SCLN | QUOT |
 * |------+------+------+------+------+------+---------------------------+------+------+------+------+------+------+------|
 * |LSFT_T|  Z   |  X   |  C   |  V   |  B   | END  |                    | PGDN |  N   |  M   | COMM | DOT  | SLSH | ENT  |
 * |-------------+------+------+------+------+------+------+------+------+------+------+------+------+------+-------------|
 * | PSCR | LGUI | LALT |LCTL_T||||||||LOWER | SPC  | DEL  |||||||| BSPC | ENT  |RAISE |||||||| LEFT | DOWN |  UP  | RGHT |
 * ,----------------------------------------------------------------------------------------------------------------------.
 *                                                                                                 generated by [keymapviz] */
  [_QWERTY] = LAYOUT( \
    KC_GRV,  KC_1,    KC_2,    KC_3,    KC_4,    KC_5,    KC_MINS,                        KC_EQL, KC_6,    KC_7,    KC_8,    KC_9,    KC_0,    KC_BSPC, \
    KC_TAB,  KC_Q,    KC_W,    KC_E,    KC_R,    KC_T,    KC_LBRC,                        KC_RBRC , KC_Y,    KC_U,    KC_I,    KC_O,    KC_P,    KC_DEL, \
    LGUI_T(KC_ESC),  KC_A,    KC_S,    KC_D,    KC_F,    KC_G,    KC_HOME ,               KC_PGUP, KC_H,    KC_J,    KC_K,    KC_L,    KC_SCLN, KC_QUOT, \
    LSFT_T(KC_F12), KC_Z,    KC_X,    KC_C,    KC_V,    KC_B,    KC_END ,                 KC_PGDN , KC_N,    KC_M,    KC_COMM, KC_DOT,  KC_SLSH, KC_ENT, \
    KC_PSCR, KC_LGUI, KC_LALT, LCTL_T(KC_F16),      LOWER,   KC_SPC ,KC_DEL,         KC_BSPC,KC_ENT , RAISE,            KC_LEFT, KC_DOWN, KC_UP,   KC_RGHT  \
  ),

/*
 * ,----------------------------------------------------------------------------------------------------------------------.
 * | GRV  |  1   |  2   |  3   |  4   |  5   | MINS |                    | EQL  |  6   |  7   |  8   |  9   |  0   | BSPC |
 * |------+------+------+------+------+------+------+--------------------+------+------+------+------+------+------+------|
 * | TAB  |  Q   |  W   |  E   |  R   |  T   | LBRC |                    | RBRC |  Y   |  U   |  I   |  O   |  P   |LALT(K|
 * |------+------+------+------+------+------+------+--------------------+------+------+------+------+------+------+------|
 * |LGUI_T|  A   |  S   |  D   |  F   |  G   | HOME |                    | PGUP |  H   |  J   |  K   |  L   |LALT(K|LALT(K|
 * |------+------+------+------+------+------+---------------------------+------+------+------+------+------+------+------|
 * |LSFT_T|  Z   |  X   |  C   |  V   |  B   | END  |                    | PGDN |  N   |  M   | COMM | DOT  | SLSH | ENT  |
 * |-------------+------+------+------+------+------+------+------+------+------+------+------+------+------+-------------|
 * | PSCR | LGUI | LALT |LCTL_T||||||||LOWER | SPC  | DEL  |||||||| BSPC | ENT  |RAISE |||||||| LEFT | DOWN |  UP  | RGHT |
 * ,----------------------------------------------------------------------------------------------------------------------.
 *                                                                                                 generated by [keymapviz] */
  [_SWE] = LAYOUT( \
    KC_GRV,  KC_1,    KC_2,    KC_3,    KC_4,    KC_5,    KC_MINS,                        KC_EQL, KC_6,    KC_7,    KC_8,    KC_9,    KC_0,    KC_BSPC, \
    KC_TAB,  KC_Q,    KC_W,    KC_E,    KC_R,    KC_T,    KC_LBRC,                        KC_RBRC , KC_Y,    KC_U,    KC_I,    KC_O,    KC_P,    LALT(KC_LBRC), \
    LGUI_T(KC_ESC),  KC_A,    KC_S,    KC_D,    KC_F,    KC_G,    KC_HOME ,               KC_PGUP, KC_H,    KC_J,    KC_K,    KC_L,    LALT(KC_SCLN), LALT(KC_QUOT), \
    LSFT_T(KC_F12), KC_Z,    KC_X,    KC_C,    KC_V,    KC_B,    KC_END ,                 KC_PGDN , KC_N,    KC_M,    KC_COMM, KC_DOT,  KC_SLSH, KC_ENT, \
    KC_PSCR, KC_LGUI, KC_LALT, LCTL_T(KC_F16),      LOWER,   KC_SPC ,KC_DEL,         KC_BSPC,KC_ENT , RAISE,            KC_LEFT, KC_DOWN, KC_UP,   KC_RGHT  \
  ),

/*
 * ,----------------------------------------------------------------------------------------------------------------------.
 * | F11  |  F1  |  F2  |  F3  |  F4  |  F5  |      |                    |      |  F6  |  F7  |  F8  |  F9  | F10  | F12  |
 * |------+------+------+------+------+------+------+--------------------+------+------+------+------+------+------+------|
 * |      |      |      | LPRN | LCBR | LBRC |      |                    |      | RBRC | RCBR | RPRN |      |      |      |
 * |------+------+------+------+------+------+------+--------------------+------+------+------+------+------+------+------|
 * |      |      |      |      |      | PGUP |      |                    |      |      | UNDS | PLUS | LCBR | RCBR | PIPE |
 * |------+------+------+------+------+------+---------------------------+------+------+------+------+------+------+------|
 * | CAPS | F17  | F18  | F19  | F10  | PGDN |      |                    |      |      |      |      |      |      | CAPS |
 * |-------------+------+------+------+------+------+------+------+------+------+------+------+------+------+-------------|
 * |      |      |      |      ||||||||      |LOWER |      ||||||||      |RAISE |      ||||||||      |      |      |      |
 * ,----------------------------------------------------------------------------------------------------------------------.
 *                                                                                                 generated by [keymapviz] */
  [_LOWER] = LAYOUT( \
    KC_F11,  KC_F1,   KC_F2,   KC_F3,   KC_F4,   KC_F5,   _______,                            _______, KC_F6,   KC_F7,   KC_F8,   KC_F9,   KC_F10,  KC_F12,  \
    _______, _______, _______, KC_LPRN, KC_LCBR, KC_LBRC, _______,                            _______, KC_RBRC, KC_RCBR, KC_RPRN, _______, _______, _______, \
    _______, _______, _______, _______, _______, KC_PGUP, _______,                            _______, _______, KC_UNDS, KC_PLUS, KC_LCBR, KC_RCBR, KC_PIPE, \
    KC_CAPS, KC_F17, KC_F18, KC_F19, KC_F10, KC_PGDN, _______,                            _______, _______, _______, _______, _______, _______, KC_CAPS, \
    _______, _______, _______, _______,          _______, LOWER,   _______,          _______, RAISE,   _______,          _______, _______, _______, _______  \
  ),

/*
 * ,----------------------------------------------------------------------------------------------------------------------.
 * | F11  |  F1  |  F2  |  F3  |  F4  |  F5  |      |                    |      |  F6  |  F7  |  F8  |  F9  | F10  | F12  |
 * |------+------+------+------+------+------+------+--------------------+------+------+------+------+------+------+------|
 * |      |      |      |  UP  | LCBR | LBRC |      |                    |      |LCTL(K|PRVWD |  UP  |NXTWD |DLINE |      |
 * |------+------+------+------+------+------+------+--------------------+------+------+------+------+------+------+------|
 * |      |      | LEFT | DOWN |RIGHT |      | END  |                    |      |LCTL(K|MINUS |EQUAL |LBRACK|RBRACK|BSLASH|
 * |------+------+------+------+------+------+---------------------------+------+------+------+------+------+------+------|
 * | CAPS | F17  | F18  | F19  | F10  |      |      |                    |      |      |      | MPRV | MNXT | MPLY | CAPS |
 * |-------------+------+------+------+------+------+------+------+------+------+------+------+------+------+-------------|
 * |      |      |      |      ||||||||      |LOWER |      ||||||||      |RAISE |      ||||||||      |      |      |      |
 * ,----------------------------------------------------------------------------------------------------------------------.
 *                                                                                                 generated by [keymapviz] */
  [_RAISE] = LAYOUT( \
    KC_F11,  KC_F1,   KC_F2,   KC_F3,   KC_F4,   KC_F5,   _______,                            _______, KC_F6,   KC_F7,   KC_F8,   KC_F9,   KC_F10,  KC_F12,  \
    _______, _______, _______, KC_UP, KC_LCBR, KC_LBRC, _______,                            _______, LCTL(KC_UP), PRVWD,   KC_UP, NXTWD,DLINE, _______, \
    _______, _______, KC_LEFT,  KC_DOWN,  KC_RIGHT, _______, KC_END,                             _______, LCTL(KC_DOWN),  KC_MINUS, KC_EQUAL, KC_LBRACKET,  KC_RBRACKET, KC_BSLASH, \
    KC_CAPS, KC_F17, KC_F18, KC_F19, KC_F10, _______, _______,                            _______, _______, _______, KC_MPRV, KC_MNXT, KC_MPLY, KC_CAPS, \
    _______, _______, _______, _______,          _______, LOWER,   _______,          _______, RAISE,            _______, _______, _______, _______, _______  \
  ),

/*
 * ,----------------------------------------------------------------------------------------------------------------------.
 * |      |      |      |      |      |      |      |                    |      |      |      |      |      |      |      |
 * |------+------+------+------+------+------+------+--------------------+------+------+------+------+------+------+------|
 * |      |      |      |BL_STE|BL_TOG|      |      |                    |      |      |RGB_TO|RGB_MO|      |      |      |
 * |------+------+------+------+------+------+------+--------------------+------+------+------+------+------+------+------|
 * |RESET |      |      |BL_BRT|CG_TOG|      |      |                    |      |      |QWERTY| SWE  |RGB_VA|      |      |
 * |------+------+------+------+------+------+---------------------------+------+------+------+------+------+------+------|
 * |      |      |      |      |BL_DEC|      |      |                    |      |      |RGB_HU|RGB_SA|RGB_VA|      |      |
 * |-------------+------+------+------+------+------+------+------+------+------+------+------+------+------+-------------|
 * |      |      |      |      ||||||||      |LOWER |      ||||||||      |RAISE |      ||||||||      |      |      |      |
 * ,----------------------------------------------------------------------------------------------------------------------.
 *                                                                                                 generated by [keymapviz] */
  [_ADJUST] = LAYOUT( \
    XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,                            XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, \
    XXXXXXX, XXXXXXX, XXXXXXX, BL_STEP, BL_TOGG, XXXXXXX, XXXXXXX,                            XXXXXXX, XXXXXXX, RGB_TOG, RGB_MOD, XXXXXXX, XXXXXXX, XXXXXXX, \
    RESET,   XXXXXXX, XXXXXXX, BL_BRTG, CG_TOGG,  XXXXXXX, XXXXXXX,                            XXXXXXX, XXXXXXX, QWERTY, SWE, RGB_VAI, XXXXXXX, XXXXXXX, \
    XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, BL_DEC,  XXXXXXX, XXXXXXX,                            XXXXXXX, XXXXXXX, RGB_HUD, RGB_SAD, RGB_VAD, XXXXXXX, XXXXXXX, \
    XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,          XXXXXXX, LOWER,   XXXXXXX,          XXXXXXX, RAISE,   XXXXXXX,          XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX  \
  )
};

bool process_record_user(uint16_t keycode, keyrecord_t *record) {
    switch (keycode) {
        case QWERTY:
            if (record->event.pressed) {
                set_single_persistent_default_layer(_QWERTY);
            }
            return false;
        case SWE:
            if (record->event.pressed) {
                set_single_persistent_default_layer(_SWE);
            }
            return false;
        case LOWER:
            if (record->event.pressed) {
                layer_on(_LOWER);
                update_tri_layer(_LOWER, _RAISE, _ADJUST);
            } else {
                layer_off(_LOWER);
                update_tri_layer(_LOWER, _RAISE, _ADJUST);
            }
            return false;
        case RAISE:
            if (record->event.pressed) {
                layer_on(_RAISE);
                update_tri_layer(_LOWER, _RAISE, _ADJUST);
            } else {
                layer_off(_RAISE);
                update_tri_layer(_LOWER, _RAISE, _ADJUST);
            }
            return false;
        case ADJUST:
            if (record->event.pressed) {
                layer_on(_ADJUST);
            } else {
                layer_off(_ADJUST);
            }
            return false;
        case PRVWD:
            if (record->event.pressed) {
                if (keymap_config.swap_lctl_lgui) {
                    register_mods(mod_config(MOD_LALT));
                    register_code(KC_LEFT);
                } else {
                    register_mods(mod_config(MOD_LCTL));
                    register_code(KC_LEFT);
                }
            } else {
                if (keymap_config.swap_lctl_lgui) {
                    unregister_mods(mod_config(MOD_LALT));
                    unregister_code(KC_LEFT);
                } else {
                    unregister_mods(mod_config(MOD_LCTL));
                    unregister_code(KC_LEFT);
                }
            }
            break;
        case NXTWD:
             if (record->event.pressed) {
                if (keymap_config.swap_lctl_lgui) {
                    register_mods(mod_config(MOD_LALT));
                    register_code(KC_RIGHT);
                } else {
                    register_mods(mod_config(MOD_LCTL));
                    register_code(KC_RIGHT);
                }
            } else {
                if (keymap_config.swap_lctl_lgui) {
                    unregister_mods(mod_config(MOD_LALT));
                    unregister_code(KC_RIGHT);
                } else {
                    unregister_mods(mod_config(MOD_LCTL));
                    unregister_code(KC_RIGHT);
                }
            }
            break;
        case LSTRT:
            if (record->event.pressed) {
                if (keymap_config.swap_lctl_lgui) {
                     //CMD-arrow on Mac, but we have CTL and GUI swapped
                    register_mods(mod_config(MOD_LCTL));
                    register_code(KC_LEFT);
                } else {
                    register_code(KC_HOME);
                }
            } else {
                if (keymap_config.swap_lctl_lgui) {
                    unregister_mods(mod_config(MOD_LCTL));
                    unregister_code(KC_LEFT);
                } else {
                    unregister_code(KC_HOME);
                }
            }
            break;
        case LEND:
            if (record->event.pressed) {
                if (keymap_config.swap_lctl_lgui) {
                    //CMD-arrow on Mac, but we have CTL and GUI swapped
                    register_mods(mod_config(MOD_LCTL));
                    register_code(KC_RIGHT);
                } else {
                    register_code(KC_END);
                }
            } else {
                if (keymap_config.swap_lctl_lgui) {
                    unregister_mods(mod_config(MOD_LCTL));
                    unregister_code(KC_RIGHT);
                } else {
                    unregister_code(KC_END);
                }
            }
            break;
        case DLINE:
            if (record->event.pressed) {
                register_mods(mod_config(MOD_LCTL));
                register_code(KC_BSPC);
            } else {
                unregister_mods(mod_config(MOD_LCTL));
                unregister_code(KC_BSPC);
            }
            break;
    }
    return true;
}
